name: MLflow CI with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my_ml_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Verify Conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      # ✅ Tambahan: Autentikasi DagsHub agar bisa akses MLflow
      - name: Authenticate with DagsHub
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://Evameivina:${DAGSHUB_TOKEN}@dagshub.com" > ~/.git-credentials

      - name: Configure Git (safe directory)
        shell: bash -l {0}
        run: |
          git config --global --add safe.directory /__w/Workflow-CI/Workflow-CI
          git config --global user.email "evameivina@example.com"
          git config --global user.name "Eva Meivina"

      # ✅ Jalankan training script (kalau ada modelling.py)
      - name: Run model training
        shell: bash -l {0}
        run: |
          python MLProject/modelling.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: evameivina/mlflow:latest
